#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Astro-FITS-Header
version:      2.8.1
version_from: 
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
