---
abstract: 'Object-oriented interface to FITS HDUs'
author:
  - 'Alasdair Allan <aa@astro.ex.ac.uk>'
  - 'Tim Jenness <tjenness@cpan.org>'
  - 'Brad Cavanagh <b.cavanagh@jach.hawaii.edu>'
  - 'Craig DeForest <deforest@boulder.swri.edu>'
  - 'Jim Lewis <jrl@ast.cam.ac.uk>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.3
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120630'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Astro-FITS-Header
provides:
  Astro::FITS::Header:
    file: lib/Astro/FITS/Header.pm
    version: 3.04
  Astro::FITS::Header::AST:
    file: lib/Astro/FITS/Header/AST.pm
    version: 3.01
  Astro::FITS::Header::CFITSIO:
    file: lib/Astro/FITS/Header/CFITSIO.pm
    version: 3.02
  Astro::FITS::Header::GSD:
    file: lib/Astro/FITS/Header/GSD.pm
    version: 3.01
  Astro::FITS::Header::Item:
    file: lib/Astro/FITS/Header/Item.pm
    version: 3.02
  Astro::FITS::Header::NDF:
    file: lib/Astro/FITS/Header/NDF.pm
    version: 3.02
  Astro::FITS::HeaderCollection:
    file: lib/Astro/FITS/Header.pm
    version: 3.01
recommends:
  Astro::FITS::CFITSIO: 0
  Starlink::AST: 0
resources:
  homepage: http://github.com/timj/perl-Astro-FITS-Header/tree/master
  license: http://opensource.org/licenses/gpl-license.php
  repository: git://github.com/timj/perl-Astro-FITS-Header.git
version: 3.07
